
swagger:
  enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9gtu4pe3f6vom022o.mysql.rds.aliyuncs.com/ideamake_wkww?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: wkww_user
    password: DVmY0F8pE74SxGaF
  web:
    filter:
      enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: flanche
    timeout: 60s
    database: 1

oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAIUVAUFuF2KHWq
  accessKeySecret: uskPD7Dn4iuCRaf2vO3I48FrPSAx2E
  bucketName: imoss
  host: cdn.ideamake.cn




#logging:
#  config: classpath:conf/logback-dev.xml
